name: GitHub Action flow to Docker hub 

on:
  push:
    branches: [main]

jobs:
  build-push-images:
    name: Zadanie 2.2
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./dockerfile.v1
          platforms: linux/amd64, linux/arm64/v8, linux/arm/v7 
          push: true
          tags: pioblaz/zadanie2:tag2
